# Generated by Django 5.1.4 on 2025-01-03 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loan_return_due_date_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 20, 31, 48, 502046, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
