# Generated by Django 5.1.4 on 2025-01-06 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_loan_return_due_date_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 17, 53, 31, 370025, tzinfo=datetime.timezone.utc)),
        ),
    ]
